// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Express   = require("./FFI/express.bs.js");
var Express$1 = require("express");

function handle_get(str, _, r) {
  return Express.send(r, str);
}

function arg(_, param) {
  return Express.send(param, "some other path");
}

function arg$1(_, param) {
  return Express.send(param, "root!");
}

((function (param) {
        return Express.listen(param, 2112);
      })((function (param) {
            return Express.get(param, "/what", arg);
          })((function (param) {
                return Express.get(param, "/", arg$1);
              })(Express$1()))));

exports.handle_get = handle_get;
/*  Not a pure module */
