// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Micro = require("micro");

var server = Micro((function (_, _$1) {
        return "Hello world!";
      }));

server.listen(2112);

exports.server = server;
/* server Not a pure module */
