// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function listen(app, port) {
  app.listen(port);
  return /* () */0;
}

function get(app, path, cb) {
  return app.get(path, cb);
}

function send(res, body) {
  return res.send(body);
}

exports.listen = listen;
exports.get    = get;
exports.send   = send;
/* No side effect */
